import { DEFAULT_LOCALE, LOCALES, type LocaleCode } from "./locales";
import type { ConstraintExplanation } from "../lib/engine/constraints";
import type { UnaffordableReasonDetail } from "../lib/engine/explain";
import { formatUSD } from "../lib/format";

/**
 * User-visible copy for the calculator components and their client scripts.
 * Components read it via their `locale` prop; client scripts via the
 * `data-locale` attribute on the calculator root (see `calculatorCopyFor`).
 */
const en = {
  common: {
    calculate: "Calculate",
    shareLabel: "Share this exact scenario",
    copyLink: "Copy link",
    copied: "Copied!",
    whyThisMatters: "Why this matters",
    resetToRecommended: "Reset to recommended",
    yourResult: "Your result",
    notAffordableYet: "Not affordable at this price yet",
    upTo: " — up to ",
    sustainUpTo: "You can actually sustain up to",
    incomeAndDebts: "Income & debts",
    grossIncome: "Annual household income (gross)",
    netIncome: "Monthly take-home pay (net)",
    otherDebts: "Other monthly debt payments",
    realLifeExpenses: "Real-life monthly expenses",
    childcare: "Childcare",
    healthcare: "Healthcare",
    groceries: "Groceries",
    transport: "Transport",
    other: "Other",
    homePrice: "Home price",
    downPayment: "Down payment",
    state: "State",
    creditBand: "Credit score band",
    rateOverride: "Interest rate override (%)",
    loanTerm: "Loan term",
    termYears: (years: number) => `${years}-year`,
    rentersInsurance: "Renters insurance (monthly)",
    utilities: "Utilities (monthly)",
  },
  tiers: {
    comfortable: "Comfortable",
    stretch: "Stretch",
    risky: "Risky",
    unaffordable: "Unaffordable",
  } as Record<string, string>,
  scale: {
    ariaLabel: (comfortableMax: number, stretchMax: number, riskyMax: number, evaluatedPrice: number) =>
      `Affordability scale: Comfortable up to ${formatUSD(comfortableMax)}, Stretch up to ${formatUSD(stretchMax)}, Risky up to ${formatUSD(riskyMax)}. Evaluated price ${formatUSD(evaluatedPrice)}.`,
  },
  affordability: {
    expensesNote: "Lenders don't count these against you — but they determine whether the payment actually fits.",
    loanAssumptions: "Loan assumptions",
    downPaymentAvailable: "Down payment available",
    hoaMonthly: "HOA dues (monthly)",
    testPrice: "Test a specific home price",
    whatWouldNeedToChange: "What would need to change",
    lenderApproves: "A lender would likely approve up to",
    gap: (gap: number) => `That's a ${formatUSD(gap)} gap — a lender may approve more home than your household's real budget can comfortably carry.`,
    noGap: "Your budget can support at least as much as a lender's generous debt-to-income ceiling — the DTI limit isn't what's holding you back here.",
    monthlyCostAt: (price: number) => `Monthly cost at ${formatUSD(price)}`,
    principalInterest: "Principal & interest",
    propertyTax: "Property tax",
    homeInsurance: "Homeowner's insurance",
    pmi: "PMI",
    pmiDrops: (month: number) => `(drops at month ${month})`,
    hoa: "HOA dues",
    lenderPayment: "Lender-counted payment (P&I + tax + insurance + PMI + HOA)",
    maintenance: "Maintenance reserve (1%/yr)",
    trueMonthlyCost: "True monthly cost",
    leftoverLabel: "Left over each month after this payment, other debts, and real-life expenses",
    canSustain: "This household clears both the lender's ratios and a real monthly budget.",
    cannotSustain: "This household would run a monthly deficit at this price — even though a lender may still approve it.",
    whatsDriving: "What's driving this",
    whatWouldChange: "What would change this",
    sensRateLabel: "Interest rate ±1 point",
    sensRateNote: "Max affordable price a point lower, at today's rate, and a point higher.",
    sensIncomeLabel: "If income dropped 20%",
    sensIncomeNote: (grossMonthly: number) => `At ${formatUSD(grossMonthly)}/mo gross, holding this home price constant.`,
    sensChildLabel: "If adding a child",
    sensChildNote: (added: number) => `Assumes +${formatUSD(added)}/mo in childcare, a national-average illustrative figure.`,
    sensDownLabel: (extra: string) => `With $${extra} more down`,
    perMonthChange: (from: number, to: number) => `${formatUSD(from)} → ${formatUSD(to)}/mo`,
    pmiChange: (from: number, to: number) => `PMI: ${formatUSD(from)} → ${formatUSD(to)}/mo`,
    /** English copy is generated by the engine itself. */
    constraint: (c: ConstraintExplanation): string => c.description,
    unaffordableReasons: (reasons: string[], _details: UnaffordableReasonDetail[]): string[] => reasons,
  },
  amortization: {
    loan: "Loan",
    extraPayment: "Extra monthly payment",
    eyebrow: "Amortization schedule",
    loanAmount: "Loan amount",
    payoffTime: "Payoff time",
    totalInterest: "Total interest paid",
    fromExtra: "From your extra payment",
    saved: (amount: number) => `${formatUSD(amount)} saved`,
    monthsSaved: (months: number) => `${months} months removed from the loan`,
    year: "Year",
    principalPaid: "Principal paid",
    interestPaid: "Interest paid",
    endingBalance: "Ending balance",
    duration: (months: number) => {
      const y = Math.floor(months / 12);
      const m = months % 12;
      if (y === 0) return `${m} mo`;
      if (m === 0) return `${y} yr`;
      return `${y} yr ${m} mo`;
    },
  },
  budget: {
    expensesNote: `"Other" here is treated as discretionary spending (Wants) — everything else below is treated as a Need.`,
    otherDiscretionary: "Other (discretionary)",
    housingPayment: "Housing payment",
    monthlyHousingPayment: "Monthly housing payment",
    housingNote: "Defaults to the sustainable monthly cost from your affordability scenario. Override this if you're renting or testing a different number.",
    resetToCalculated: "Reset to calculated",
    eyebrow: "Your budget",
    heading: "50/30/20 breakdown",
    warningTitle: "Housing alone exceeds your entire Needs target",
    warningBody: "Your housing payment by itself is more than 50% of your net income — before groceries, transportation, or anything else in the Needs category.",
    needs: "Needs",
    wants: "Wants",
    savings: "Savings / debt paydown",
    target: (pct: string) => `target ${pct}`,
    delta: (delta: number) => (delta > 0 ? `${formatUSD(delta)} over target` : `${formatUSD(Math.abs(delta))} under target`),
  },
  car: {
    expensesNote: "Lenders don't count these against you — but they determine whether the car payment actually fits.",
    carLoanAssumptions: "Car & loan assumptions",
    stateForTax: "State (for sales tax)",
    tradeIn: "Trade-in value",
    termMonths: (months: number) => `${months}mo`,
    autoInsurance: "Auto insurance (monthly)",
    rateDisclosure: (asOf: string) => `Default auto loan rates shown are static baselines as of ${asOf}, not a live feed — override with your own quote for an exact number.`,
    testPrice: "Test a specific car price",
    ruleAllows: "The 20/4/10 rule would allow up to",
    gap: (gap: number) => `That's a ${formatUSD(gap)} gap — the rule of thumb allows more car than your household's real budget can comfortably carry.`,
    noGap: "Your budget can support at least as much as the 20/4/10 rule's ceiling — the rule of thumb isn't what's holding you back here.",
    costBreakdownAt: (price: number) => `Cost breakdown at ${formatUSD(price)}`,
    salesTax: "Sales tax (financed into the loan)",
    amountFinanced: "Amount financed",
    monthlyPrincipalInterest: "Monthly principal & interest",
    monthlyInsurance: "Monthly insurance",
    totalMonthlyCost: "Total monthly cost",
    excludes: "Doesn't include fuel, maintenance, or registration — this is the financing cost only.",
    leftoverLabel: "Left over each month after this car payment, other debts, and real-life expenses",
    canSustain: "This household clears both the 20/4/10-style ratio and a real monthly budget.",
    cannotSustain: "This household would run a monthly deficit at this price — even though it may look affordable by the ratio alone.",
  },
  rent: {
    rentCosts: "Rent-specific costs",
    bindingRules: {
      income: "30% of gross income",
      screening: "40x annual income (landlord screening)",
      leftover: "Leftover income after real expenses",
    } as Record<string, string>,
    incomeRow: "30% of gross income",
    screeningRow: "40x annual income (screening)",
    leftoverRow: "Leftover income after real expenses",
    maxRent: "Max affordable rent",
    boundBy: "Bound by:",
    explainer:
      "The 30% rule and the 40x screening rule are mathematically the same threshold — landlords verify it strictly against gross annual income. The leftover-income rule often binds tighter once renters insurance, utilities, and real-life expenses are counted.",
    testRent: "Test a specific rent",
    leftoverLabel: "Left over each month at this rent",
    overBudget: "This rent is above what this household can sustainably afford by any of the three rules.",
    clears: "This rent clears all three affordability rules.",
  },
  rentVsBuy: {
    buyingScenario: "Buying scenario",
    rentingScenario: "Renting scenario",
    monthlyRent: "Monthly rent",
    timeline: "Timeline",
    yearsInHome: "Expected years in the home",
    atYears: (years: number) => `At ${years} years`,
    choices: { buy: "Buying", rent: "Renting", "roughly equal": "Roughly a tie" } as Record<string, string>,
    aheadBy: "comes out ahead by",
    breakeven: (year: number) => `Buying overtakes renting in net worth around year ${year}.`,
    noBreakeven: "Buying doesn't overtake renting in net worth within 30 years at these assumptions.",
    chartAria: "Net worth over time: buying versus renting",
    legendBuy: "Buying net worth",
    legendRent: "Renting net worth",
    buyerAtYear: (year: number) => `Buying net worth at year ${year}`,
    renterAtYear: (year: number) => `Renting net worth at year ${year}`,
    assumptions: "Assumes 3% annual home appreciation, 6% investment return on the money not spent buying, 3% annual rent growth, and 6% selling costs. See the",
    methodologyLink: "methodology",
    assumptionsEnd: "for the full model.",
  },
  closing: {
    purchase: "Purchase",
    eyebrow: "Cash needed at closing",
    typical: "typical",
    range: (low: number, high: number) => `Range: ${formatUSD(low)} – ${formatUSD(high)}`,
    ccLow: "Closing costs (low, 2%)",
    ccTypical: "Closing costs (typical, 3%)",
    ccHigh: "Closing costs (high, 5%)",
    totalCash: "Total cash needed (typical)",
    note: "This is cash on top of the down payment — lender fees, title insurance, appraisal, recording fees, and similar one-time costs. It's frequently the thing first-time buyers forget to budget for.",
  },
  og: {
    unaffordableTitle: (state: string) => `What it would take to afford a home in ${state} — TrueAfford`,
    unaffordableDescription: "This scenario doesn't clear affordability thresholds yet. See exactly what would need to change.",
    title: (price: number, state: string) => `This household can afford up to ${formatUSD(price)} in ${state} — TrueAfford`,
    description: (comfortableMax: number, stretchMax: number, riskyMax: number) =>
      `Comfortable up to ${formatUSD(comfortableMax)}, Stretch up to ${formatUSD(stretchMax)}, Risky up to ${formatUSD(riskyMax)}. Full monthly breakdown, no ads in the result.`,
  },
};

export type CalculatorCopy = typeof en;

const es: CalculatorCopy = {
  common: {
    calculate: "Calcular",
    shareLabel: "Comparte este escenario exacto",
    copyLink: "Copiar enlace",
    copied: "¡Copiado!",
    whyThisMatters: "Por qué importa",
    resetToRecommended: "Volver al recomendado",
    yourResult: "Tu resultado",
    notAffordableYet: "Aún no es asequible a este precio",
    upTo: " — hasta ",
    sustainUpTo: "Realmente puedes sostener hasta",
    incomeAndDebts: "Ingresos y deudas",
    grossIncome: "Ingreso anual del hogar (bruto)",
    netIncome: "Ingreso mensual neto",
    otherDebts: "Otros pagos mensuales de deudas",
    realLifeExpenses: "Gastos mensuales reales",
    childcare: "Cuidado infantil",
    healthcare: "Atención médica",
    groceries: "Comestibles",
    transport: "Transporte",
    other: "Otros",
    homePrice: "Precio de la vivienda",
    downPayment: "Enganche",
    state: "Estado",
    creditBand: "Rango de puntaje de crédito",
    rateOverride: "Tasa de interés personalizada (%)",
    loanTerm: "Plazo del préstamo",
    termYears: (years: number) => `${years} años`,
    rentersInsurance: "Seguro de inquilino (mensual)",
    utilities: "Servicios (mensual)",
  },
  tiers: {
    comfortable: "Cómodo",
    stretch: "Ajustado",
    risky: "Riesgoso",
    unaffordable: "No asequible",
  },
  scale: {
    ariaLabel: (comfortableMax, stretchMax, riskyMax, evaluatedPrice) =>
      `Escala de asequibilidad: Cómodo hasta ${formatUSD(comfortableMax)}, Ajustado hasta ${formatUSD(stretchMax)}, Riesgoso hasta ${formatUSD(riskyMax)}. Precio evaluado ${formatUSD(evaluatedPrice)}.`,
  },
  affordability: {
    expensesNote: "Los prestamistas no cuentan estos gastos en tu contra — pero determinan si el pago realmente cabe en tu presupuesto.",
    loanAssumptions: "Supuestos del préstamo",
    downPaymentAvailable: "Enganche disponible",
    hoaMonthly: "Cuotas de HOA (mensual)",
    testPrice: "Prueba un precio de vivienda específico",
    whatWouldNeedToChange: "Qué tendría que cambiar",
    lenderApproves: "Un prestamista probablemente aprobaría hasta",
    gap: (gap) => `Es una diferencia de ${formatUSD(gap)} — un prestamista puede aprobar más vivienda de la que el presupuesto real de tu hogar puede sostener con comodidad.`,
    noGap: "Tu presupuesto puede sostener al menos lo que permite el generoso límite deuda-ingreso de un prestamista — el límite DTI no es lo que te está frenando aquí.",
    monthlyCostAt: (price) => `Costo mensual a ${formatUSD(price)}`,
    principalInterest: "Capital e intereses",
    propertyTax: "Impuesto predial",
    homeInsurance: "Seguro de vivienda",
    pmi: "PMI",
    pmiDrops: (month) => `(se elimina en el mes ${month})`,
    hoa: "Cuotas de HOA",
    lenderPayment: "Pago que cuenta el prestamista (capital e intereses + impuesto + seguro + PMI + HOA)",
    maintenance: "Reserva de mantenimiento (1%/año)",
    trueMonthlyCost: "Costo mensual real",
    leftoverLabel: "Lo que te queda cada mes después de este pago, otras deudas y gastos reales",
    canSustain: "Este hogar cumple tanto las relaciones del prestamista como un presupuesto mensual real.",
    cannotSustain: "Este hogar tendría un déficit mensual a este precio — aunque un prestamista todavía lo apruebe.",
    whatsDriving: "Qué está determinando esto",
    whatWouldChange: "Qué cambiaría esto",
    sensRateLabel: "Tasa de interés ±1 punto",
    sensRateNote: "Precio máximo asequible con un punto menos, a la tasa actual y con un punto más.",
    sensIncomeLabel: "Si el ingreso bajara 20%",
    sensIncomeNote: (grossMonthly) => `Con ${formatUSD(grossMonthly)}/mes brutos, manteniendo constante este precio de vivienda.`,
    sensChildLabel: "Si se suma un hijo",
    sensChildNote: (added) => `Supone +${formatUSD(added)}/mes en cuidado infantil, una cifra ilustrativa del promedio nacional.`,
    sensDownLabel: (extra) => `Con $${extra} más de enganche`,
    perMonthChange: (from, to) => `${formatUSD(from)} → ${formatUSD(to)}/mes`,
    pmiChange: (from, to) => `PMI: ${formatUSD(from)} → ${formatUSD(to)}/mes`,
    constraint: (c) => {
      const amount = formatUSD(c.monthlyImpact);
      switch (c.id) {
        case "other-debts":
          return `Tus ${amount}/mes en otros pagos de deudas están reduciendo tu precio máximo en aproximadamente ${formatUSD(c.priceImpact ?? 0)}.`;
        case "state-property-tax":
          return `El impuesto predial de ${c.stateName}, de ${(c.taxRatePct ?? 0).toFixed(2)}%, te está costando aproximadamente ${amount}/mes más de lo que sugeriría el promedio nacional.`;
        case "state-insurance":
          return `El seguro de vivienda en ${c.stateName} te está costando aproximadamente ${amount}/mes más de lo que sugeriría el promedio nacional.`;
        case "pmi":
          return `El seguro hipotecario privado (PMI) te está costando ${amount}/mes porque tu enganche es menor al 20%. ${formatUSD(c.additionalDownPayment ?? 0)} adicionales de enganche lo eliminarían.`;
        case "real-life-expenses":
          return c.priceImpact !== null
            ? `Tus ${amount}/mes en cuidado infantil, atención médica, comestibles y otros gastos reales están reduciendo tu precio máximo en aproximadamente ${formatUSD(c.priceImpact)} — los prestamistas no los cuentan, pero son reales.`
            : `Tus ${amount}/mes en cuidado infantil, atención médica, comestibles y otros gastos reales no afectan lo que un prestamista aprobará, pero reducen directamente lo que te queda cada mes.`;
      }
    },
    unaffordableReasons: (_reasons, details) =>
      details.map((d) => {
        switch (d.id) {
          case "no-income":
            return "No se ingresó un ingreso mensual bruto, así que no se puede calcular la relación deuda-ingreso del prestamista.";
          case "housing-ratio":
            return `Solo el pago de vivienda ocuparía ${d.pct}% del ingreso bruto — por encima del límite de 36% que los prestamistas generalmente permiten. Un precio menor, un enganche mayor o una tasa más baja lo reducirían.`;
          case "total-dti":
            return `Sumando otras deudas, las obligaciones mensuales totales llegarían a ${d.pct}% del ingreso bruto — por encima del límite de 50% que los prestamistas generalmente permiten. Pagar otras deudas liberaría espacio aquí.`;
          case "leftover-deficit":
            return `Aunque las relaciones deuda-ingreso se cumplen, el hogar quedaría ${formatUSD(d.amount)}/mes en negativo después de los gastos reales. Esa brecha tendría que cerrarse con más ingresos, menos gastos o un préstamo menor.`;
          case "generic":
            return "Este escenario no supera los umbrales de asequibilidad a este precio. Prueba un precio menor o un enganche mayor.";
        }
      }),
  },
  amortization: {
    loan: "Préstamo",
    extraPayment: "Pago mensual adicional",
    eyebrow: "Tabla de amortización",
    loanAmount: "Monto del préstamo",
    payoffTime: "Tiempo para liquidar",
    totalInterest: "Interés total pagado",
    fromExtra: "Gracias a tu pago adicional",
    saved: (amount) => `${formatUSD(amount)} ahorrados`,
    monthsSaved: (months) => `${months} meses menos de préstamo`,
    year: "Año",
    principalPaid: "Capital pagado",
    interestPaid: "Interés pagado",
    endingBalance: "Saldo final",
    duration: (months) => {
      const y = Math.floor(months / 12);
      const m = months % 12;
      const years = y === 1 ? "1 año" : `${y} años`;
      const rest = m === 1 ? "1 mes" : `${m} meses`;
      if (y === 0) return rest;
      if (m === 0) return years;
      return `${years} ${rest}`;
    },
  },
  budget: {
    expensesNote: `Aquí "Otros" se trata como gasto discrecional (Deseos) — todo lo demás se trata como una Necesidad.`,
    otherDiscretionary: "Otros (discrecional)",
    housingPayment: "Pago de vivienda",
    monthlyHousingPayment: "Pago mensual de vivienda",
    housingNote: "Por defecto usa el costo mensual sostenible de tu escenario de asequibilidad. Cámbialo si alquilas o quieres probar otra cifra.",
    resetToCalculated: "Volver al calculado",
    eyebrow: "Tu presupuesto",
    heading: "Desglose 50/30/20",
    warningTitle: "Solo la vivienda supera toda tu meta de Necesidades",
    warningBody: "Tu pago de vivienda por sí solo es más del 50% de tu ingreso neto — antes de comestibles, transporte o cualquier otra cosa de la categoría Necesidades.",
    needs: "Necesidades",
    wants: "Deseos",
    savings: "Ahorro / pago de deudas",
    target: (pct) => `meta ${pct}`,
    delta: (delta) => (delta > 0 ? `${formatUSD(delta)} por encima de la meta` : `${formatUSD(Math.abs(delta))} por debajo de la meta`),
  },
  car: {
    expensesNote: "Los prestamistas no cuentan estos gastos en tu contra — pero determinan si el pago del auto realmente cabe en tu presupuesto.",
    carLoanAssumptions: "Supuestos del auto y del préstamo",
    stateForTax: "Estado (para el impuesto sobre ventas)",
    tradeIn: "Valor de tu auto a cambio",
    termMonths: (months) => `${months} meses`,
    autoInsurance: "Seguro de auto (mensual)",
    rateDisclosure: (asOf) => `Las tasas predeterminadas de préstamo de auto son referencias estáticas al ${asOf}, no datos en vivo — usa tu propia cotización para obtener una cifra exacta.`,
    testPrice: "Prueba un precio de auto específico",
    ruleAllows: "La regla 20/4/10 permitiría hasta",
    gap: (gap) => `Es una diferencia de ${formatUSD(gap)} — la regla general permite más auto del que el presupuesto real de tu hogar puede sostener con comodidad.`,
    noGap: "Tu presupuesto puede sostener al menos el límite de la regla 20/4/10 — la regla general no es lo que te está frenando aquí.",
    costBreakdownAt: (price) => `Desglose de costos a ${formatUSD(price)}`,
    salesTax: "Impuesto sobre ventas (financiado en el préstamo)",
    amountFinanced: "Monto financiado",
    monthlyPrincipalInterest: "Capital e intereses mensuales",
    monthlyInsurance: "Seguro mensual",
    totalMonthlyCost: "Costo mensual total",
    excludes: "No incluye gasolina, mantenimiento ni registro — este es solo el costo del financiamiento.",
    leftoverLabel: "Lo que te queda cada mes después de este pago del auto, otras deudas y gastos reales",
    canSustain: "Este hogar cumple tanto una relación estilo 20/4/10 como un presupuesto mensual real.",
    cannotSustain: "Este hogar tendría un déficit mensual a este precio — aunque parezca asequible solo por la relación.",
  },
  rent: {
    rentCosts: "Costos específicos del alquiler",
    bindingRules: {
      income: "30% del ingreso bruto",
      screening: "40 veces el ingreso anual (evaluación del arrendador)",
      leftover: "Ingreso sobrante después de gastos reales",
    },
    incomeRow: "30% del ingreso bruto",
    screeningRow: "40 veces el ingreso anual (evaluación)",
    leftoverRow: "Ingreso sobrante después de gastos reales",
    maxRent: "Alquiler máximo asequible",
    boundBy: "Limitado por:",
    explainer:
      "La regla del 30% y la regla de evaluación de 40 veces son matemáticamente el mismo umbral — los arrendadores la verifican estrictamente contra el ingreso bruto anual. La regla del ingreso sobrante suele ser más estricta una vez que se cuentan el seguro de inquilino, los servicios y los gastos reales.",
    testRent: "Prueba un alquiler específico",
    leftoverLabel: "Lo que te queda cada mes con este alquiler",
    overBudget: "Este alquiler supera lo que este hogar puede pagar de forma sostenible según cualquiera de las tres reglas.",
    clears: "Este alquiler cumple las tres reglas de asequibilidad.",
  },
  rentVsBuy: {
    buyingScenario: "Escenario de compra",
    rentingScenario: "Escenario de alquiler",
    monthlyRent: "Alquiler mensual",
    timeline: "Horizonte",
    yearsInHome: "Años que esperas vivir en la vivienda",
    atYears: (years) => `A ${years} años`,
    choices: { buy: "Comprar", rent: "Alquilar", "roughly equal": "Prácticamente un empate" },
    aheadBy: "sale adelante por",
    breakeven: (year) => `Comprar supera a alquilar en patrimonio neto alrededor del año ${year}.`,
    noBreakeven: "Comprar no supera a alquilar en patrimonio neto dentro de 30 años con estos supuestos.",
    chartAria: "Patrimonio neto a lo largo del tiempo: comprar frente a alquilar",
    legendBuy: "Patrimonio neto comprando",
    legendRent: "Patrimonio neto alquilando",
    buyerAtYear: (year) => `Patrimonio neto comprando en el año ${year}`,
    renterAtYear: (year) => `Patrimonio neto alquilando en el año ${year}`,
    assumptions: "Supone 3% de apreciación anual de la vivienda, 6% de rendimiento de inversión sobre el dinero no gastado en comprar, 3% de aumento anual del alquiler y 6% de costos de venta. Consulta la",
    methodologyLink: "metodología",
    assumptionsEnd: "para ver el modelo completo.",
  },
  closing: {
    purchase: "Compra",
    eyebrow: "Efectivo necesario al cierre",
    typical: "típico",
    range: (low, high) => `Rango: ${formatUSD(low)} – ${formatUSD(high)}`,
    ccLow: "Costos de cierre (bajo, 2%)",
    ccTypical: "Costos de cierre (típico, 3%)",
    ccHigh: "Costos de cierre (alto, 5%)",
    totalCash: "Efectivo total necesario (típico)",
    note: "Esto es efectivo adicional al enganche — comisiones del prestamista, seguro de título, avalúo, honorarios de registro y cargos únicos similares. Con frecuencia es lo que los compradores primerizos olvidan presupuestar.",
  },
  og: {
    unaffordableTitle: (state) => `Lo que se necesitaría para comprar una vivienda en ${state} — TrueAfford`,
    unaffordableDescription: "Este escenario aún no supera los umbrales de asequibilidad. Ve exactamente qué tendría que cambiar.",
    title: (price, state) => `Este hogar puede pagar hasta ${formatUSD(price)} en ${state} — TrueAfford`,
    description: (comfortableMax, stretchMax, riskyMax) =>
      `Cómodo hasta ${formatUSD(comfortableMax)}, Ajustado hasta ${formatUSD(stretchMax)}, Riesgoso hasta ${formatUSD(riskyMax)}. Desglose mensual completo, sin anuncios en el resultado.`,
  },
};

export const CALCULATOR_COPY: Record<LocaleCode, CalculatorCopy> = { en, es };

/** Client-side lookup: reads the `data-locale` a calculator component renders on its root. */
export function calculatorCopyFor(root: Element): CalculatorCopy {
  const code = root.getAttribute("data-locale");
  const locale = LOCALES.find((l) => l.code === code)?.code ?? DEFAULT_LOCALE;
  return CALCULATOR_COPY[locale];
}
